name: CI Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger pipeline on pushes to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set this in repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in repository secrets

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/jay:v1 .

      # Step 4: Push the Docker image
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/jay:v1